inherit_from: .rubocop_todo.yml

Lint/AmbiguousRegexpLiteral:
  Enabled: false

# def_delegators’ first symbol is the target, the rest are calls
Style/AlignParameters:
  Enabled: false

# FIXME: should this be normalised to `EnforcedStyle: semantic`?
Style/BlockDelimiters:
  Enabled: false

# including parametrised modules looks much better without this alignment
Style/ClosingParenthesisIndentation:
  Enabled: false

Style/ConstantName:
  Exclude:
    - yaks/lib/yaks/breaking_changes.rb

Style/EmptyLineBetweenDefs:
  AllowAdjacentOneLineDefs: true

# including parametrised modules looks much better without this indentation
Style/FirstParameterIndentation:
  Enabled: false

Style/HashSyntax:
  Exclude:
    - Rakefile

# some arrays need deeper indenting for readability
Style/IndentArray:
  Enabled: false

Style/IndentationWidth:
  Exclude:
    - yaks/lib/yaks/breaking_changes.rb

# the codebase uses -> consistently
Style/Lambda:
  Enabled: false

# FIXME: figure out why fixing this blows tests up
Style/MethodCallParentheses:
  Enabled: false

Style/ModuleFunction:
  Exclude:
    - yaks/lib/yaks/util.rb

Style/PercentLiteralDelimiters:
  Exclude:
    - yaks/lib/yaks/breaking_changes.rb
    - yaks/spec/unit/yaks/config_spec.rb

Style/Semicolon:
  AllowAsExpressionSeparator: true

Style/SignalException:
  EnforcedStyle: only_raise

# FIXME: this should be enforced to either space or no_space
Style/SpaceBeforeBlockBraces:
  Enabled: false

# FIXME: this should be enforced to either space or no_space
Style/SpaceInsideBlockBraces:
  Enabled: false

# FIXME: make a call whether to fix this one or not
Style/SpaceInsideBrackets:
  Enabled: false

Style/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

# FIXME: enforce either single_quotes (fewer fixes) or double_quotes
Style/StringLiterals:
  Enabled: false

Style/UnneededPercentQ:
  Exclude:
    - yaks/lib/yaks/breaking_changes.rb
