language: ruby
script: bundle exec rake $TASK
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - ruby-head
  - rbx
  - jruby
  - jruby-head
env:
  - TASK=yaks:rspec
  - TASK=yaks-html:rspec
  - TASK=mutant
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: rbx
    - env: TASK=mutant
  exclude:
    - rvm: jruby
      env: TASK=mutant
    - rvm: jruby-head
      env: TASK=mutant