language: ruby
script: "bundle exec rspec"
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.1
  - rbx
  - jruby
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: rbx
    - rvm: jruby
    - rvm: ruby-head
    - rvm: jruby-head
