language: ruby

rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - jruby
  - jruby-head
  - rbx
  - ruby-head

sudo: false

script: bundle exec rake $TASK

env:
  - TASK=yaks:rspec
  - TASK=yaks-html:rspec
  - TASK=mutant

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
    - env: TASK=mutant
  exclude:
    - rvm: 1.9.3
      env: TASK=mutant
    - rvm: 2.0
      env: TASK=mutant
    - rvm: 2.1
      env: TASK=mutant
    - rvm: jruby
      env: TASK=mutant
    - rvm: jruby-head
      env: TASK=mutant
    - rvm: rbx
      env: TASK=mutant
    - rvm: 2.1
      env: TASK=ruby-head
